# Maicraft 客户端配置模板
# 将此文件复制为 config.yaml 并根据需要修改。

minecraft:
  host: 127.0.0.1        # Minecraft 服务器地址
  port: 25565            # 端口
  username: MaiBot       # 机器人用户名（离线模式）
  password:              # 在线模式密码（offline 留空）
  auth: offline          # offline | microsoft | mojang
  version: "1.19.0"      # 可选，留空自动检测

enabledEvents:
  - chat
  - playerJoin
  - playerLeave
  - mobSpawn
  - blockBreak
  - blockPlace
  - healthUpdate
  - experienceUpdate
  - weatherChange

# 日志配置
logging:
  level: INFO             # DEBUG | INFO | WARN | ERROR
  enableFileLog: true     # 是否启用文件日志
  logFilePath: ""         # 日志文件路径，留空使用默认路径 (logs/maicraft-*.log)
  useStderr: true         # 是否使用 stderr 输出（MCP 模式建议保持 true）
  colors: true            # 是否启用颜色输出
  timestamp: true         # 是否显示时间戳

# MCP Server 配置
mcp:
  name: "Maicraft MCP"
  version: "0.1.0"
  tools:
    # 工具过滤配置（可选）
    # 方式1：黑名单模式（推荐）- 屏蔽指定工具，其他全部可用
    disabled:
      - use_chest
      - smelt_item
    # 方式2：白名单模式 - 仅暴露指定工具
    # enabled:
    #   - mine_block
    #   - place_block
    #   - follow_player
    # 方式3：同时使用 - 白名单允许的集合减去黑名单
    # enabled:
    #   - mine_block
    #   - place_block
    #   - chat
    # disabled:
    #   - chat
    # 方式4：不配置 - 默认暴露所有工具
    # （删除或注释掉 tools 部分）