# Maicraft 客户端配置模板
# 将此文件复制为 config.yaml 并根据需要修改。

minecraft:
  host: 127.0.0.1        # Minecraft 服务器地址
  port: 25565            # 端口
  username: MaiBot       # 机器人用户名（离线模式）
  password:              # 在线模式密码（offline 留空）
  auth: offline          # offline | microsoft | mojang
  version: "1.19.0"      # 可选，留空自动检测

enabledEvents:
  - chat
  - playerJoin
  - playerLeave
  - mobSpawn
  - blockBreak
  - blockPlace
  - healthUpdate
  - experienceUpdate
  - weatherChange
  - timeUpdate

maxMessageHistory: 100     # 本地最大事件缓存条数

# 日志配置
logging:
  level: INFO             # DEBUG | INFO | WARN | ERROR
  enableFileLog: true     # 是否启用文件日志
  logFilePath: ""         # 日志文件路径，留空使用默认路径 (logs/maicraft-*.log)
  useStderr: true         # 是否使用 stderr 输出（MCP 模式建议保持 true）
  colors: true            # 是否启用颜色输出
  timestamp: true         # 是否显示时间戳

# MCP Server 配置
mcp:
  name: "Maicraft MCP"
  version: "0.1.0"
  tools:
    enabled:               # 可选：仅暴露指定工具，留空则全部可用
      - mine_block
      - place_block
      - follow_player